#
# Cookbook Name:: halt
# Recipe:: packages

package 'make' 
package 'binutils' 
package 'bison' 
package 'gcc' 
package 'build-essential'
package 'curl'
package 'ubuntu-desktop'
package 'python'
package 'python-virtualenv'
package 'python3'
package 'ruby'
package 'ssh'
package 'vim'
package 'vim-gnome'
package 'tmux'
package 'git'
package 'mercurial'
package 'firefox'
package 'i3'
package 'scrot'
package 'feh'
package 'meld'
package 'rxvt-unicode-256color'
package 'xfonts-terminus'
